# Site
name: 'UQ-DS-Seminar'
description: 'Official Site for Data Science Seminar Series, The University of Queensland.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/uqds.ico'
baseurl: ''
disqus: 'https-uq-ds-seminar-github-io'
email: 'y.luo@uq.edu.au'
mailchimp-list: 'https://github.us17.list-manage.com/subscribe/post?u=ece2482ceaa4d8663c8de0eb4&amp;id=f0fe41106a'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

  
authors:
    yadan:
      name:           Yadan Luo
      site:           https://luoyadan.github.io/
      bio:            ""
      email:          y.luo@uq.edu.au
     
# Dimensions
max_width: 1080px

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events